const actionTypes = {
    START_TIMER: 'START_TIMER',
    TOGGLE_PLAY_PAUSE: 'TOGGLE_PLAY_PAUSE',
    INCREASE_BREAK_VALUE: 'INCREASE_BREAK_VALUE',
    DECREASE_BREAK_VALUE: 'DECREASE_BREAK_VALUE',
    INCREASE_SESSION_VALUE: 'INCREASE_SESSION_VALUE',
    DECREASE_SESSION_VALUE: 'DECREASE_SESSION_VALUE',
    RESET_TIMER: 'RESET_TIMER',
    TOGGLE_TIMER_LABEL: 'TOGGLE_TIMER_LABEL'
}

export default actionTypes;
